project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: labs.qmd
        text: Labs
      - href: projects.qmd
        text: Projects
      - href: presentations.qmd
        text: Presentations

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

